/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.radimkolacny.chess.forms;

import cz.radimkolacny.chess.TextCompiler;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author radimkolacny
 */
public class EndGameJDialog extends javax.swing.JDialog {

    public EndGameJDialog(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        chessFrame = (ChessJFrame) parent;
        
        initComponents();
        
        setupPanelOfComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endGameJPanel = new javax.swing.JPanel();
        reportJLabel = new javax.swing.JLabel();
        menuJButton = new javax.swing.JButton();
        closeJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("End of game");
        setResizable(false);

        reportJLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        reportJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportJLabel.setInheritsPopupMenu(false);
        reportJLabel.setMinimumSize(new java.awt.Dimension(300, 50));
        reportJLabel.setPreferredSize(new java.awt.Dimension(500, 50));

        menuJButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        menuJButton.setText("Main Menu");
        menuJButton.setMinimumSize(new java.awt.Dimension(100, 35));
        menuJButton.setPreferredSize(new java.awt.Dimension(100, 35));
        menuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJButtonActionPerformed(evt);
            }
        });

        closeJButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        closeJButton.setText("Close");
        closeJButton.setMinimumSize(new java.awt.Dimension(100, 35));
        closeJButton.setPreferredSize(new java.awt.Dimension(100, 35));
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout endGameJPanelLayout = new javax.swing.GroupLayout(endGameJPanel);
        endGameJPanel.setLayout(endGameJPanelLayout);
        endGameJPanelLayout.setHorizontalGroup(
            endGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endGameJPanelLayout.createSequentialGroup()
                .addGroup(endGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endGameJPanelLayout.createSequentialGroup()
                        .addComponent(menuJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(endGameJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reportJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)))
                .addContainerGap())
        );
        endGameJPanelLayout.setVerticalGroup(
            endGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endGameJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(endGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(endGameJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(endGameJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupPanelOfComponents(){
        
        GridBagLayout layout = new GridBagLayout();
        endGameJPanel.setLayout(layout);
        GridBagConstraints gbc = new GridBagConstraints();
 
        // Put constraints on different components
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 0;
        reportJLabel.setText(TextCompiler.getEndGameOutput());
        endGameJPanel.add(reportJLabel, gbc);
 
        gbc.gridx = 0;
        gbc.gridy = 2;
        endGameJPanel.add(menuJButton, gbc);
 
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridwidth = 2;
        endGameJPanel.add(closeJButton, gbc);
        
        this.add(endGameJPanel);

        setLocationRelativeTo(null);
    }

    
    private void menuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJButtonActionPerformed
        chessFrame.getNewGame().getMainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuJButtonActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndGameJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndGameJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndGameJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndGameJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JPanel endGameJPanel;
    private javax.swing.JButton menuJButton;
    private javax.swing.JLabel reportJLabel;
    // End of variables declaration//GEN-END:variables

    private final ChessJFrame chessFrame;
    private String endGameOutput;

    public String getEndGameOutput() {
        return endGameOutput;
    }
}
