/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.radimkolacny.chess.forms;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author radimkolacny
 */
public class PromotePawnJDialog extends javax.swing.JDialog {

    public PromotePawnJDialog(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        chessJFrame = (ChessJFrame) parent;
        colorOfSelectedFigure = chessJFrame.getChessGame().getGameManager().getSelectedFigure().getColorOfImage();
        
        initComponents();
        
        loadImagesToCollection();
        setIconsForButtons();
        setupDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promoteFigureJPanel = new javax.swing.JPanel();
        rookJButton = new javax.swing.JButton();
        queenJButton = new javax.swing.JButton();
        knightJButton = new javax.swing.JButton();
        bishopJButton = new javax.swing.JButton();
        chooseFigureJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(140, 200));
        setModal(true);
        setSize(new java.awt.Dimension(140, 200));

        promoteFigureJPanel.setPreferredSize(new java.awt.Dimension(140, 200));

        rookJButton.setPreferredSize(new java.awt.Dimension(60, 60));
        rookJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rookJButtonActionPerformed(evt);
            }
        });

        queenJButton.setPreferredSize(new java.awt.Dimension(60, 60));
        queenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queenJButtonActionPerformed(evt);
            }
        });

        knightJButton.setPreferredSize(new java.awt.Dimension(60, 60));
        knightJButton.setSize(new java.awt.Dimension(100, 100));
        knightJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knightJButtonActionPerformed(evt);
            }
        });

        bishopJButton.setPreferredSize(new java.awt.Dimension(60, 60));
        bishopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bishopJButtonActionPerformed(evt);
            }
        });

        chooseFigureJLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        chooseFigureJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseFigureJLabel.setText("Promote Pawn");

        javax.swing.GroupLayout promoteFigureJPanelLayout = new javax.swing.GroupLayout(promoteFigureJPanel);
        promoteFigureJPanel.setLayout(promoteFigureJPanelLayout);
        promoteFigureJPanelLayout.setHorizontalGroup(
            promoteFigureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoteFigureJPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(rookJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bishopJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promoteFigureJPanelLayout.createSequentialGroup()
                .addGroup(promoteFigureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promoteFigureJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(queenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(knightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promoteFigureJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chooseFigureJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        promoteFigureJPanelLayout.setVerticalGroup(
            promoteFigureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoteFigureJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseFigureJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(promoteFigureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(knightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(promoteFigureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rookJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bishopJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(promoteFigureJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(promoteFigureJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void queenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queenJButtonActionPerformed
        selectFigureForPromote = "queen";
        dispose();
    }//GEN-LAST:event_queenJButtonActionPerformed

    private void bishopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bishopJButtonActionPerformed
        selectFigureForPromote = "bishop";
        dispose();
    }//GEN-LAST:event_bishopJButtonActionPerformed

    private void knightJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knightJButtonActionPerformed
        selectFigureForPromote = "knight";
        dispose();
    }//GEN-LAST:event_knightJButtonActionPerformed

    private void rookJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rookJButtonActionPerformed
        selectFigureForPromote = "rook";
        dispose();
    }//GEN-LAST:event_rookJButtonActionPerformed

    private void loadImagesToCollection(){
        ImageIcon iconForFigureInDialog;
        for(String nameOfFigure : namesOfFigures){
            iconForFigureInDialog = new ImageIcon(path + colorOfSelectedFigure + nameOfFigure + ".png");
            Image resizedImage = iconForFigureInDialog.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            ImageIcon resizedImageIcon = new ImageIcon(resizedImage);
            iconsForFiguresInDialog.add(resizedImageIcon);
        }
    }
    
    private void setIconsForButtons(){
        queenJButton.setIcon(iconsForFiguresInDialog.get(0));
        rookJButton.setIcon(iconsForFiguresInDialog.get(1));
        knightJButton.setIcon(iconsForFiguresInDialog.get(2));
        bishopJButton.setIcon(iconsForFiguresInDialog.get(3));
    }
    
    private void setupDialog(){
        setLocationRelativeTo(null);
        setBackground(Color.WHITE);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        pack();
        setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromotePawnJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromotePawnJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromotePawnJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromotePawnJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bishopJButton;
    private javax.swing.JLabel chooseFigureJLabel;
    private javax.swing.JButton knightJButton;
    private javax.swing.JPanel promoteFigureJPanel;
    private javax.swing.JButton queenJButton;
    private javax.swing.JButton rookJButton;
    // End of variables declaration//GEN-END:variables
    private final ChessJFrame chessJFrame;
    private String selectFigureForPromote = null;
    private String colorOfSelectedFigure;
    private List<ImageIcon> iconsForFiguresInDialog = new ArrayList<>();
    private final String[] namesOfFigures = {"queen","rook","knight","bishop"};
    private final String path = "src/resources/";

    public String getSelectFigureForPromote() {
        return selectFigureForPromote;
    }
    public void setSelectFigureForPromote(String selectFigureForPromote) {
        this.selectFigureForPromote = selectFigureForPromote;
    }
}
