/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.radimkolacny.chess;

import GUI.NewGameJDialog;
import GUI.PreviousGamesJDialog;
import Managers.FileManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author radimkolacny
 */
public class MainMenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuJFrame
     */
    public MainMenuJFrame() {
        initComponents();

        setMainJPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        newGameJButton = new javax.swing.JButton();
        previousGamesJButton = new javax.swing.JButton();
        exitJButton = new javax.swing.JButton();
        logoJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newGameJButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        newGameJButton.setText("NEW GAME");
        newGameJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newGameJButton.setMaximumSize(new java.awt.Dimension(250, 50));
        newGameJButton.setMinimumSize(new java.awt.Dimension(250, 50));
        newGameJButton.setPreferredSize(new java.awt.Dimension(250, 50));
        newGameJButton.setSize(new java.awt.Dimension(250, 50));
        newGameJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameJButtonActionPerformed(evt);
            }
        });

        previousGamesJButton.setFont(new java.awt.Font("Arial", 2, 21)); // NOI18N
        previousGamesJButton.setText("PREVIOUS GAMES");
        previousGamesJButton.setMaximumSize(new java.awt.Dimension(250, 50));
        previousGamesJButton.setMinimumSize(new java.awt.Dimension(200, 50));
        previousGamesJButton.setPreferredSize(new java.awt.Dimension(250, 50));
        previousGamesJButton.setSize(new java.awt.Dimension(250, 50));
        previousGamesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousGamesJButtonActionPerformed(evt);
            }
        });

        exitJButton.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        exitJButton.setText("EXIT");
        exitJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitJButton.setMaximumSize(new java.awt.Dimension(250, 50));
        exitJButton.setMinimumSize(new java.awt.Dimension(200, 50));
        exitJButton.setPreferredSize(new java.awt.Dimension(250, 50));
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        logoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousGamesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGameJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newGameJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousGamesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameJButtonActionPerformed
        NewGameJDialog newGame = new NewGameJDialog(this, true);
        newGame.setLocationRelativeTo(null);
        newGame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newGameJButtonActionPerformed

    private void previousGamesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousGamesJButtonActionPerformed
        PreviousGamesJDialog previousGames = new PreviousGamesJDialog(this, true);
    }//GEN-LAST:event_previousGamesJButtonActionPerformed

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void setMainJPanel(){
 
        setJPanelComponents();
        mainJPanel.setLayout(new BoxLayout(mainJPanel, BoxLayout.Y_AXIS));
        mainJPanel.setBackground(Color.WHITE);

        mainJPanel.add(logoJLabel);
        mainJPanel.add(Box.createRigidArea(new Dimension(0,5)));
        mainJPanel.add(newGameJButton);
        mainJPanel.add(previousGamesJButton);
        mainJPanel.add(exitJButton);
    }
    
    public void setJPanelComponents(){
        
        ImageIcon logoMainMenu = new ImageIcon("src/resources/chess_main_menu_logo.png");
        Image image = logoMainMenu.getImage();
        Image resizedImage = image.getScaledInstance(logoMainMenu.getIconWidth()/4, logoMainMenu.getIconHeight()/4, Image.SCALE_SMOOTH);
        ImageIcon resizedLogo = new ImageIcon(resizedImage);
        
        logoJLabel.setIcon(resizedLogo);
        logoJLabel.setAlignmentX(CENTER_ALIGNMENT);
        
        newGameJButton.setAlignmentX(CENTER_ALIGNMENT);
        previousGamesJButton.setAlignmentX(CENTER_ALIGNMENT);
        exitJButton.setAlignmentX(CENTER_ALIGNMENT);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenuJFrame mainMenu = new MainMenuJFrame();
                mainMenu.setVisible(true);
                mainMenu.setTitle("CHESS GAME");
        
                mainMenu.setBackground(Color.WHITE);
 
                mainMenu.setLocationRelativeTo(null);
        
                mainMenu.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
                mainMenu.setResizable(false);
                mainMenu.pack();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitJButton;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton newGameJButton;
    private javax.swing.JButton previousGamesJButton;
    // End of variables declaration//GEN-END:variables

    private final FileManager fileManager = new FileManager();

    public FileManager getFileManager() {
        return fileManager;
    }
}
