/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import cz.radimkolacny.chess.MainMenuJFrame;
import javax.swing.JLabel;

/**
 *
 * @author radimkolacny
 */
public class NewGameJDialog extends javax.swing.JDialog {

    public NewGameJDialog(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        mainMenu = (MainMenuJFrame) parent;
        
        initComponents();
        
        okJButton.setAlignmentX(CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterFirstJLabel = new javax.swing.JLabel();
        wrongFirstJLabel = new javax.swing.JLabel();
        enterSecondJLabel = new javax.swing.JLabel();
        wrongSecondJLabel = new javax.swing.JLabel();
        firstPlayerJTextField = new javax.swing.JTextField();
        secondPlayerJTextField = new javax.swing.JTextField();
        okJButton = new javax.swing.JButton();
        sameNameJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New game");

        enterFirstJLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enterFirstJLabel.setText("First player nickname:");
        enterFirstJLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        enterFirstJLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        enterFirstJLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        wrongFirstJLabel.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        wrongFirstJLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongFirstJLabel.setMinimumSize(new java.awt.Dimension(100, 10));
        wrongFirstJLabel.setPreferredSize(new java.awt.Dimension(300, 15));

        enterSecondJLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enterSecondJLabel.setText("Second player nickname:");
        enterSecondJLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        enterSecondJLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        enterSecondJLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        wrongSecondJLabel.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        wrongSecondJLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongSecondJLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        wrongSecondJLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        wrongSecondJLabel.setPreferredSize(new java.awt.Dimension(300, 15));

        firstPlayerJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstPlayerJTextField.setMaximumSize(new java.awt.Dimension(300, 30));
        firstPlayerJTextField.setMinimumSize(new java.awt.Dimension(300, 30));
        firstPlayerJTextField.setPreferredSize(new java.awt.Dimension(300, 30));

        secondPlayerJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secondPlayerJTextField.setMaximumSize(new java.awt.Dimension(300, 30));
        secondPlayerJTextField.setMinimumSize(new java.awt.Dimension(300, 30));
        secondPlayerJTextField.setPreferredSize(new java.awt.Dimension(300, 30));

        okJButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        okJButton.setText("OK");
        okJButton.setPreferredSize(new java.awt.Dimension(150, 40));
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        sameNameJLabel.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        sameNameJLabel.setForeground(new java.awt.Color(255, 0, 0));
        sameNameJLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterSecondJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(wrongSecondJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterFirstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(wrongFirstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(firstPlayerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(okJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(secondPlayerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sameNameJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterFirstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongFirstJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstPlayerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sameNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterSecondJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongSecondJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondPlayerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        
        firstName = firstPlayerJTextField.getText().trim();
        secondName = secondPlayerJTextField.getText().trim();
        
        boolean isFirstNameOk = controlEnterName(firstName, wrongFirstJLabel);
        boolean isSecondNameOk = controlEnterName(secondName, wrongSecondJLabel);
        boolean isSameName = controlSameName(firstName, secondName);
        
        if(isFirstNameOk && isSecondNameOk && !isSameName){
            ChessJFrame chessFrame = new ChessJFrame(this);
            this.setVisible(false);
        }
    }//GEN-LAST:event_okJButtonActionPerformed

    public boolean controlSameName(String firstName, String secondName){
        
        if(firstName.equals(secondName)){
            sameNameJLabel.setText("Names are SAME!!!");
            return true;
        }
        sameNameJLabel.setText("");
        return false;
    }
    
    public boolean controlEnterName(String playerName, JLabel textLabel){
        
        String wrongEnterMessage = "Name of player have to be minimal 3 characters!!!";
        
        if(playerName.length() > 2 && !playerName.isBlank()){
            textLabel.setText("");
            return true;
        }
        else{
            textLabel.setText(wrongEnterMessage);
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGameJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterFirstJLabel;
    private javax.swing.JLabel enterSecondJLabel;
    private javax.swing.JTextField firstPlayerJTextField;
    private javax.swing.JButton okJButton;
    private javax.swing.JLabel sameNameJLabel;
    private javax.swing.JTextField secondPlayerJTextField;
    private javax.swing.JLabel wrongFirstJLabel;
    private javax.swing.JLabel wrongSecondJLabel;
    // End of variables declaration//GEN-END:variables

    private MainMenuJFrame mainMenu;
    private String firstName = "";
    private String secondName = "";

    public MainMenuJFrame getMainMenu() {
        return mainMenu;
    }
    
    public void setMainMenu(MainMenuJFrame mainMenu) {
        this.mainMenu = mainMenu;
    }
    
    public String getFirstName() {
        return firstName;
    }
    
    public String getSecondName() {
        return secondName;
    }
}
